Added new rules for CMP banners
Transparency-Consent-Framework-Research/consent-crawler pull request #2
Opened 2023-02-27 21:31 UTC by pritam2406

Added rules for 3 websites.

2023-02-28 21:28 UTC, antoniojtorres requested changes
Would like to test this on at least 3 domains to ensure it's working. See the document that @rag24 is working on.

2023-02-28 21:28 UTC, antoniojtorres commented on src/util/cmp_banners.ts
> +  // https://trustarc.com/
@pritam2406 Is this the website you used to develop and verify the rule?

2023-02-28 22:16 UTC, pritam2406 commented on src/util/cmp_banners.ts
> +  // https://trustarc.com/
yes.

2023-03-01 04:33 UTC, antoniojtorres reviewed
@pritam2406 Great progress. I tested all three examples and was able to reproduce. Flickr seems straight forward, we should check if a distinct element exists using locator().count() to determine which variant we're in. I think the onetrust one has that already  you can reference.

2023-03-02 19:30 UTC, antoniojtorres commented
@pritam2406 Thank you! This PR is getting pretty big. Let's stop where it's at. I have a refactor coming that I'll need help with, it'll allow us to submit handle CMPs with many different variants, and it makes them individually testable. I'll merge this as is and then make a new branch for that. Thanks again

2023-03-02 19:31 UTC, antoniojtorres approved these changes
Approving without testing to make room for incoming refactor that adds testing.

2023-03-02 19:31 UTC, merged